title: Mysql database

steps:
  - title: Install Mysql
    class:
    code: |
      ```sh
      apt-get install mysql-server
      ```

  - title: Install PHP driver
    class: is-ubuntu-16
    code: |
      ```sh
      apt-get install php7.0-mysql
      ```

  - title: Create the database
    class:
    code: |
      ```sql
      CREATE DATABASE `example` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
      ```

  - title: Create the user and configure the privileges
    class:
    code: |
      ```sql
      CREATE USER 'example'@'localhost' IDENTIFIED BY 'password';
      GRANT ALL PRIVILEGES ON `example`.* TO 'example'@'localhost';
      FLUSH PRIVILEGES;
      ```
